version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      USERID: 33
      GROUPID: 33
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/DiskMain3T/network_storage/:/data:z
    command:
      - -p
      - -W
      - -u
      - "fox;123"
      - -s
      - "fox;/data/fox;yes;no;no;fox;fox;;Fox's space!"
      - -G
      - "fox;delete veto files = no"
      - -G
      - "fox;veto files ="
networks:
  default:
